- Fixing image check

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -298,12 +298,12 @@ jobs:
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         run: |
-          if ! [[ WEBAPP_IMAGE_ID =~ ^$ECR_REGISTRY\/$ECR_REPOSITORY:.+$ ]]; then
-            echo "Invalid Image Url"
+          if ! [[ WEBAPP_IMAGE_ID =~ ^$ECR_REGISTRY\/${{ secrets.WEBAPP_REPOSITORY_NAME }}:.+$ ]]; then
+            echo "Invalid Webapp Image Url"
             exit 1
           fi
-          if ! [[ WS_IMAGE_ID =~ ^$ECR_REGISTRY\/$ECR_REPOSITORY:.+$ ]]; then
-            echo "Invalid Image Url"
+          if ! [[ WS_IMAGE_ID =~ ^$ECR_REGISTRY\/${{ secrets.WS_REPOSITORY_NAME }}:.+$ ]]; then
+            echo "Invalid WS Image Url"
             exit 1
           fi
 
